### ISSUE TITLE
application session data

### ISSUE THREAD

**Issue by icing** [abetterinternet/crustls#81]
We install C callbacks into `server_config` which will later be invoked from `server_session` instances created for individual connections. These callbacks need access to connection related information for reasons of proper logging or use of correct memory pools for allocations.

The `server_session` should carry a `void *` application data add during its creation. Passing this to callback installed in the base `server_config` would allow an application easy and fast access to the connection context.

In the current design, this is only possible to achieve when the complete `server_config` is created again and again for each connection. Which seems not desirable. Alternatively, having the application maintain global maps of connection <->  server_session pairing seems overly complicated.

**Comment by djc** [comment]
This should be covered by https://github.com/ctz/rustls/issues/89, right? I'm working towards that.

**Comment by icing** [comment]
I guess, when the app sees the full client hello before setting up the rustls server session, this would no longer be needed, unless we find some later events we need to handle in a callback.

However, this also means that rustls server config is not really used as it seems to be intended, e.g. as a global , unmutable set of TLS configs from which sesions are created for each connection. Instead, each connection would first create its own config instance and from that a session. Because there are connection specific things (from the app point of view) which can only be modified in a config, as far as I understood.

**Comment by djc** [comment]
In my understanding, the goal of ctz/rustls#89 is to create a new type, `Acceptor`, that doesn't a `ServerConfig`. It can be fed with bytes coming in from the second, and you can call `client_hello() -> Option<ClientHello>` on it. Once `client_hello()` returns `Some`, there will be a way to create a `ServerSession` from the `Acceptor` and an `&Arc<ServerConfig>`. Thus, you can still have a small set of immutable `ServerConfig`s if desirable.

**Comment by icing** [comment]
Understood. But if you install a client cert verifier, , it is unable to log the success/failure in relation to the connection it happens on. In pseudo code:

```
setup_server(server s) {
  client_verifier cv = my_client_verifier(s);
  config = rustls_server_config(vc);
 ...
}

setup_connection(conn c) {
  server s = server_selected_by_conn( c );
  session = ServerSession(config_for_server( s ));
  ...
}
```

The `client_verifier::verify_client_cert()` is later invoked by the `ServerSession`, but it has no way to find the connection `c`, or? without some global map.

**Comment by jsha** [comment]
To make this concrete: Maybe the [ClientCertVerifier](https://docs.rs/rustls/0.19.0/rustls/trait.ClientCertVerifier.html) implementation wants to be able to log "failed client cert validation for connection from 1.2.3.4:19845. Subject = Foo. Issuer = Bar". I agree with what you say, @icing: this is not doable with the current ClientCertVerifier design, unless you use thread-locals / global map.

In https://github.com/ctz/rustls/issues/438, we came to the conclusion that the solution for delivering rustls' own logging to the user code should be via thread locals. Perhaps we could use the same mechanism for logging within callbacks?

If we added a state parameter to ClientCertVerifier it might look something like:

```
pub fn verify_client_cert(
    &self,
    state: Any,
    presented_certs: &[Certificate],
    sni: Option<&DNSName>
) -> Result<ClientCertVerified, TLSError>
```

I don't like this approach because it turns `verify_client_cert` from a pure function with defined inputs and outputs to one that could take a lot of hidden inputs via `state`.

You mentioned logging and allocator pools. If we can find a good solution to the logging, do you think it's possible to also solve the allocator pools? How do those work in Apache?

**Comment by icing** [comment]
I am not very much enthusiastic about using thread locals. The reason being that a failure to clean them up properly may lead to using the `wrong` instance variable. Apache has all connection relevant things tied to a `conn_rec *c` from where all other context information is retrieved. Also the memory pool to use for that connection.

Now, memory pools in Apache are not thread safe and in my `mod_http2` work I had to fight cases where a pool was used from the wrong thread, e.g. concurrently, and that gets wonderful memory mess ups based on runtime behaviour. Heisenbugs.

To be more constructive: my idead would be that all session related callbacks get the `ServerSession` aka `rustls_server_session` as parameter. And when creating the session, the application may pass a `void *app_data`, which becomes an immutable and retrievable part of a ServerSession. From my pov we could then also remove the `userdata` parameter we have now for the callbacks.

Several `C` libraries use this design pattern and it seems to me that there is really no cost involved. In regard to logging, I am not familiar what Rust logging offers here, but passing the `ServerSession` instance along would then also solve that problem.

**Comment by djc** [comment]
To go back to the original use cases, (a) logging and (b) use of the correct memory pool, I think we effectively already agreed to use thread locals for determine the correct logging context, right?

I don't think we'll want to internalize an `*app_data` into rustls `Session` types, so I think it follows that that will need to become part of the crustls `rustls_server_session`... but then, assuming we have multiple sessions per config, there is still no way for the `rustls_server_session` to pass that value into the certificate verifier impl, right? So we'd end up using a thread local anyway to manage that, I guess? I suppose maybe we could wrap the certificate verifier in an `Arc` and hold a reference to it that allows us to stuff the `*app_data` in there before calling `process_new_packets()` on the session, but in my mind that's pretty much equivalent to using a thread local.

Assuming we're not going to make changes to the rustls `Session` types for this (and that seems like a hard sell to me), I don't think there's a good alternative to thread locals. But, we could use thread locals on the Rust side, where we could maybe use RAII/`Drop` to make cleaning them up more misuse-resistant?

**Comment by icing** [comment]
> To go back to the original use cases, (a) logging and (b) use of the correct memory pool, I think we effectively already agreed to use thread locals for determine the correct logging context, right?

I have not seen any API related things to logging and cannot judge if there would be agreement in the Apache use case.

> I don't think we'll want to internalize an `*app_data` into rustls `Session` types, so I think it follows that that will need to become part of the crustls `rustls_server_session`... but then, assuming we have multiple sessions per config, there is still no way for the `rustls_server_session` to pass that value into the certificate verifier impl, right? So we'd end up using a thread local anyway to manage that, I guess? I suppose maybe we could wrap the certificate verifier in an `Arc` and hold a reference to it that allows us to stuff the `*app_data` in there before calling `process_new_packets()` on the session, but in my mind that's pretty much equivalent to using a thread local.

I do not understand the reluctance to have 'app_data' in the Session. Could you explain?

> Assuming we're not going to make changes to the rustls `Session` types for this (and that seems like a hard sell to me), I don't think there's a good alternative to thread locals. But, we could use thread locals on the Rust side, where we could maybe use RAII/`Drop` to make cleaning them up more misuse-resistant?

Maybe I was not clear enough: Apache will not use thread locals to store connection records. This is a security issue based on past, bad experiences.

**Comment by djc** [comment]
> I have not seen any API related things to logging and cannot judge if there would be agreement in the Apache use case.

The logging issue was discussed [here](https://github.com/ctz/rustls/issues/438).

> I do not understand the reluctance to have 'app_data' in the Session. Could you explain?

To be clear, I have not verified this with Joe. But, on the Rust side it seems we have done well without this, and storing an untyped pointer in the Rust `Session` types seems pretty unidiomatic. I don't think Rust users maybe don't mind using thread locals that much?

> Maybe I was not clear enough: Apache will not use thread locals to store connection records. This is a security issue based on past, bad experiences.

I read that as saying that you don't want use thread locals in C. However, I thought you might not mind as much if thread locals were used on the Rust side of the FFI boundary, where I think we a have any number of tools to make their usage much less risky. Would you not want to use a Rust API that relies on thread locals (in the grand scheme of things, how would you know)?

**Comment by icing** [comment]
> > I have not seen any API related things to logging and cannot judge if there would be agreement in the Apache use case.
> 
> The logging issue was discussed [here](https://github.com/ctz/rustls/issues/438).

Thanks for the pointer. I meant I have not seen what @jsha wants to do here.

> > I do not understand the reluctance to have 'app_data' in the Session. Could you explain?
> 
> To be clear, I have not verified this with Joe. But, on the Rust side it seems we have done well without this, and storing an untyped pointer in the Rust `Session` types seems pretty unidiomatic. I don't think Rust users maybe don't mind using thread locals that much?

I can' t speak for other applications, obviously. I think the gap comes from the difference between designing an application in the Rust spirit of immutable objects and embedding it into a vast, existing infrastructure that does not follow this.
 
> > Maybe I was not clear enough: Apache will not use thread locals to store connection records. This is a security issue based on past, bad experiences.
> 
> I read that as saying that you don't want use thread locals in C. However, I thought you might not mind as much if thread locals were used on the Rust side of the FFI boundary, where I think we a have any number of tools to make their usage much less risky. Would you not want to use a Rust API that relies on thread locals (in the grand scheme of things, how would you know)?

Having connection instances, which are mutable and not thread safe, in global memory (and that is what a thread local is), is really unacceptable in my case. We can share war stories about past disaster over a beer one day, hopefully.

But let's say `crustls` takes on this job. Now, where does it get the application data from that it needs to put into the thread local? Is this then a parameter in every `crustls` method? Or does `crustls` manage to tie this to a session somehow without it being a member of the session instance? Note that this needs to be re-entrant and cope with nested sessions as well (a callback that indirectly uses another rustls session).

How do you see this working?

**Comment by djc** [comment]
> Note that this needs to be re-entrant and cope with nested sessions as well (a callback that indirectly uses another rustls session).

Why do we need to cope with nested sessions?

I was thinking a `rustls_server_session` could store the application data, and we could design an API such that methods on its inner fields can only be called from a guard type that takes care of managing the thread local, replacing it when the guard type is instantiated as well as when it is dropped. I think this would probably still work even if we need nested sessions, which I had not thought about, but I guess we'd have to try.

**Comment by icing** [comment]
The server is a highly configurable piece of software and not a static executable. There are loadable 3rd party modules and hooks for plugging in things everywhere. When one module calls server infrastructure, all kinds of things can be invoked. 

For example: for storing TLS session data, a caching instance can be configured. That is a storage framework with loadable implementations <https://httpd.apache.org/docs/current/socache.html>. For example a [redis](https://httpd.apache.org/docs/current/mod/mod_socache_redis.html) based implementation. That one, as far as I know, does not use TLS connections, but it might one day. Or there might be one out there, I do not know of.

If we bring libraries into the server that are not re-entrant, this would pose a challenge. We do not want to say "you cannot load more than one rust module" or "only those two can be loaded, unless you load this other one".

rustls needs to document what its contract is in this regard. I assume that `curl` has related demands because it juggles not only many sessions in the same thread, but also needs to do name resolving and that might open a `https` connections for DoH queries. If that can trigger nested calls, i do not know. 

But complexity is there and global variables are a thing to avoid. If we can glue related data to session instances, it makes things just that easier.

**Comment by djc** [comment]
@ctz any thoughts about this issue?

**Comment by jsha** [comment]
I agree with @djc that an an untyped pointer in rustls' `Session` type is unidiomatic, and I'd be reluctant to recommend it. I also agree with @icing that global variables are a thing to avoid. And I've seen a similar problem, in curl, to the one @icing's working with for Apache. That's what spurred me to file https://github.com/ctz/rustls/issues/438: curl has no global logging facility, but has per-request logging facilities. That's a mismatch for Rust's global logger. As we discussed on ctz/rustls#438, fixing the mismatch would mean plumbing through a logging context in a large number of rustls types, and would be quite disruptive.

The issue of global vs per-request logging (and tracing) is a pretty universal one. Rust's `log` format makes a purity concession (globals) to gain significant convenience. Go's very basic log system does the same thing. However, there's an important use case of "distributed tracing," where you collect a sample of performance data as it goes through multiple processes and systems (e.g. RPCs triggering other RPCs and so on). For that purpose, Go uses a `context.Context`: https://blog.golang.org/context. This has to be passed through as the first argument of every function that's part of a context-using call. It's somewhat tedious, but is explicit and doesn't use globals. As I understand it, most other languages use thread locals for this sort of distributed tracing. Go can't because it doesn't expose the concept of threads, only goroutines; and the Go designers are quite firm that there should be no such thing as a "goroutine id."

For crustls, I'd like to try a demonstration of what @djc suggests: make `rustls_server_session` and `rustls_client_session` into a struct containing two elements: a `userdata` pointer and a `*mut ServerSession` / `*mut ClientSession` (to be updated to `...Connection` soon). We would have a thread local on the Rust side: `userdata: Option<*mut c_void>`. In each of the crustls functions that deals with a session, we would set `userdata` on entry, and clear it on exit. We incorporate this into a wrapper macro to make it hard to forget. We'd test the viability of this by hooking it up with curl's per-request logging (or Apache's logging, if @icing is interested in giving that a shot).

**Comment by djc** [comment]
FWIW, I completely agree that global state is something to avoid in general. Unfortunately I do think this is a more or less appropriate solution for the particular domains of both logging and allocation pools. (As far as I know, Rust's tracing would indeed rely on thread locals, at least in the tracing + opentelemetry variants I've used.)

I do think with appropriate use of Rust's type system we can shore up most of the downsides of thread locals.

**Comment by icing** [comment]
FTR: we are mixing things here. The logging would need a varying instance, depending what is currently in use. The connection glued to a ServerSession would remain constant throughout the lifetime of the session. We are storing untyped pointers in crustls as `userdata` callback args. I just wanted to highlight that.

I think I expressed my disgust about thread locals sufficiently already, so nothing to add here.😌

**Comment by jsha** [comment]
> We are storing untyped pointers in crustls as userdata callback args. I just wanted to highlight that.

This is true, but this is specific to crustls. I'm totally fine with untyped userdata callback args in crustls, because those are required in order to do any sort of callback in C. And the userdata callback args only show up in the crustls API, not the Rust rustls API. The problem here is that to make things work right for this specific use case, we'd have to make that untyped userdata parameter part of the Rust rustls API - and it would feel very out of place there.

If we can find a way to store the untyped userdata parameter associated with a `rustls_server_session`, without making it part of the Rust rustls API, and also without using thread locals, I would be very happy. But I can't think of such a way right now.

**Comment by jsha** [comment]
I put up #83 to give an idea of what a possible solution could look like. Critiques very welcome!
